FROM centos
RUN echo -e '[mongodb-org-3.2]\nname=MongoDB Repository\nbaseurl=https://repo.mongodb.org/yum/redhat/$releasever/mongodb-org/3.2/x86_64/\ngpgcheck=0\nenabled=1' > /etc/yum.repos.d/mongodb-org-3.2.repo
RUN yum install -y mongodb-org
